version: '3'
services:
  grobid:
    image: lfoppiano/grobid:0.7.3
    container_name: grobid
    ports:
      - "8070:8070"
    environment:
      - JAVA_OPTS=-Xmx6g -Dorg.grobid.max.connections=20 -Dorg.grobid.processors=10 -Dorg.grobid.timeout=120000 -XX:-UseContainerSupport
    volumes:
      - ./data:/opt/grobid/data
      - ./logs:/opt/grobid/logs
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8070/api/isalive"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s